/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventoryManagement;

/**
 *
 * @author cpypr
 */
public class pnlCategory extends javax.swing.JPanel {

    /**
     * Creates new form pnlCategory
     */
    public pnlCategory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrCategories = new javax.swing.JScrollPane();
        lstInventory = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnEditQuantity = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblInventory = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 280));
        setPreferredSize(new java.awt.Dimension(400, 280));
        setLayout(null);

        scrCategories.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lstInventory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lstInventory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstInventoryMouseClicked(evt);
            }
        });
        scrCategories.setViewportView(lstInventory);

        add(scrCategories);
        scrCategories.setBounds(10, 60, 200, 180);

        btnAdd.setBackground(new java.awt.Color(221, 221, 221));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAdd.setText("ADD ITEM");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.setMaximumSize(new java.awt.Dimension(63, 23));
        btnAdd.setMinimumSize(new java.awt.Dimension(63, 23));
        btnAdd.setPreferredSize(new java.awt.Dimension(63, 23));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(240, 80, 140, 40);

        btnEditQuantity.setBackground(new java.awt.Color(221, 221, 221));
        btnEditQuantity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEditQuantity.setText("EDIT QUANTITY");
        btnEditQuantity.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditQuantity.setMaximumSize(new java.awt.Dimension(63, 23));
        btnEditQuantity.setMinimumSize(new java.awt.Dimension(63, 23));
        btnEditQuantity.setPreferredSize(new java.awt.Dimension(63, 23));
        btnEditQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQuantityActionPerformed(evt);
            }
        });
        add(btnEditQuantity);
        btnEditQuantity.setBounds(240, 130, 140, 40);

        btnRemove.setBackground(new java.awt.Color(221, 221, 221));
        btnRemove.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRemove.setText("REMOVE ITEM");
        btnRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemove.setMaximumSize(new java.awt.Dimension(63, 23));
        btnRemove.setMinimumSize(new java.awt.Dimension(63, 23));
        btnRemove.setPreferredSize(new java.awt.Dimension(63, 23));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove);
        btnRemove.setBounds(240, 180, 140, 40);

        lblInventory.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblInventory.setText("(Category) Stock:");
        add(lblInventory);
        lblInventory.setBounds(10, 20, 380, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lstInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstInventoryMouseClicked
        System.out.println("item clicked");
    }//GEN-LAST:event_lstInventoryMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        System.out.println("Add Button Pressed!");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQuantityActionPerformed
        System.out.println("Edit Quantity Button Pressed!");
    }//GEN-LAST:event_btnEditQuantityActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        System.out.println("Remove Button Pressed!");
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEditQuantity;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JList<String> lstInventory;
    private javax.swing.JScrollPane scrCategories;
    // End of variables declaration//GEN-END:variables
}
