package InventoryManagement;

import javax.swing.JOptionPane;

public class pnlCategory extends javax.swing.JPanel {

    /**
     * Creates new form pnlCategory
     */
    public pnlCategory() {
        initComponents();

        //Set visibilities
        defaultVisibility();
    }

    public void setCategoryLabel(String name) {
        lblInventory.setText(name + " Stock:");
    }

    public void defaultVisibility() {
        pnlButtons.setVisible(true);
        pnlEditQuantity.setVisible(false);
    }

    private boolean checkItemSelected() {
        boolean itemSelected = false;

        if (lstInventory.getSelectedValue() != null) {
            itemSelected = true;
        } else { //item not selected
            JOptionPane.showMessageDialog(null, "Please select an item", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        return itemSelected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInventory = new javax.swing.JLabel();
        scrCategories = new javax.swing.JScrollPane();
        lstInventory = new javax.swing.JList<>();
        pnlButtons = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEditQuantity = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        pnlEditQuantity = new javax.swing.JPanel();
        spnQuantity = new javax.swing.JSpinner();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(175, 199, 249));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setPreferredSize(new java.awt.Dimension(400, 280));
        setLayout(null);

        lblInventory.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblInventory.setText("(Category) Stock:");
        add(lblInventory);
        lblInventory.setBounds(10, 20, 380, 30);

        scrCategories.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lstInventory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lstInventory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", "item 1", "item 2", "item 3", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstInventoryMouseClicked(evt);
            }
        });
        scrCategories.setViewportView(lstInventory);

        add(scrCategories);
        scrCategories.setBounds(10, 60, 180, 180);

        pnlButtons.setBackground(new java.awt.Color(175, 199, 249));

        btnAdd.setBackground(new java.awt.Color(221, 221, 221));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAdd.setText("ADD ITEM");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.setMaximumSize(new java.awt.Dimension(63, 23));
        btnAdd.setMinimumSize(new java.awt.Dimension(63, 23));
        btnAdd.setPreferredSize(new java.awt.Dimension(63, 23));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEditQuantity.setBackground(new java.awt.Color(221, 221, 221));
        btnEditQuantity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEditQuantity.setText("EDIT QUANTITY");
        btnEditQuantity.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditQuantity.setMaximumSize(new java.awt.Dimension(63, 23));
        btnEditQuantity.setMinimumSize(new java.awt.Dimension(63, 23));
        btnEditQuantity.setPreferredSize(new java.awt.Dimension(63, 23));
        btnEditQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQuantityActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(221, 221, 221));
        btnRemove.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRemove.setText("REMOVE ITEM");
        btnRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemove.setMaximumSize(new java.awt.Dimension(63, 23));
        btnRemove.setMinimumSize(new java.awt.Dimension(63, 23));
        btnRemove.setPreferredSize(new java.awt.Dimension(63, 23));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        add(pnlButtons);
        pnlButtons.setBounds(190, 60, 210, 180);

        pnlEditQuantity.setBackground(new java.awt.Color(175, 199, 249));

        spnQuantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnConfirm.setBackground(new java.awt.Color(221, 221, 221));
        btnConfirm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnConfirm.setText("CONFIRM");
        btnConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirm.setMaximumSize(new java.awt.Dimension(63, 23));
        btnConfirm.setMinimumSize(new java.awt.Dimension(63, 23));
        btnConfirm.setPreferredSize(new java.awt.Dimension(63, 23));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(221, 221, 221));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.setMaximumSize(new java.awt.Dimension(63, 23));
        btnCancel.setMinimumSize(new java.awt.Dimension(63, 23));
        btnCancel.setPreferredSize(new java.awt.Dimension(63, 23));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditQuantityLayout = new javax.swing.GroupLayout(pnlEditQuantity);
        pnlEditQuantity.setLayout(pnlEditQuantityLayout);
        pnlEditQuantityLayout.setHorizontalGroup(
            pnlEditQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(pnlEditQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditQuantityLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlEditQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEditQuantityLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlEditQuantityLayout.setVerticalGroup(
            pnlEditQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(pnlEditQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditQuantityLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(pnlEditQuantity);
        pnlEditQuantity.setBounds(190, 60, 210, 180);
    }// </editor-fold>//GEN-END:initComponents

    private void lstInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstInventoryMouseClicked
        System.out.println("item clicked");
    }//GEN-LAST:event_lstInventoryMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        System.out.println("Add Button Pressed!");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQuantityActionPerformed
        System.out.println("Edit Quantity Button Pressed!");

        if (checkItemSelected()) { //error checking
            pnlButtons.setVisible(false);
            pnlEditQuantity.setVisible(true);
        }
    }//GEN-LAST:event_btnEditQuantityActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        System.out.println("Remove Button Pressed!");

        if (checkItemSelected()) { //error checking
            int confirm = JOptionPane.showConfirmDialog(null, "Remove " + lstInventory.getSelectedValue(), "CONFIRMATION", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                System.out.println("yes");
            } else {
                System.out.println("no");
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        System.out.println("confirmed quantity change");

        /*send info to controller
         */
        defaultVisibility();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        defaultVisibility();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnEditQuantity;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JList<String> lstInventory;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlEditQuantity;
    private javax.swing.JScrollPane scrCategories;
    private javax.swing.JSpinner spnQuantity;
    // End of variables declaration//GEN-END:variables
}
